### ISSUE TITLE
Add appveyor support

### ISSUE THREAD

**Issue by satazor** [IndigoUnited/node-detect-readme-badges#25]
You may check the bower repository for an example.

//cc @carsy

**Comment by carsy** [comment]
On it 😄

**Comment by carsy** [comment]
for reference: https://raw.githubusercontent.com/bower/bower/master/README.md

**Comment by satazor** [comment]
Actually you already got some of them listed here: https://github.com/IndigoUnited/node-detect-readme-badges/blob/master/lib/coveralls.js#L3

It would be cool to have the most important ones, such as appveyor and the coverage ones which is heavily used by npms.
